# Generated by Django 5.1.7 on 2025-03-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Not provided'),
        ),
    ]
