# Generated by Django 5.1.7 on 2025-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0015_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='A3CA31003E', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
