# Generated by Django 5.1.7 on 2025-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0017_alter_referral_referral_code_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='666750A3B4', max_length=10, unique=True),
        ),
    ]
