# Generated by Django 5.1.7 on 2025-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0018_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='A4AF258840', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
