# Generated by Django 5.1.7 on 2025-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0020_alter_referral_referral_code_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='7A26590ED6', max_length=10, unique=True),
        ),
    ]
