# Generated by Django 5.1.7 on 2025-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0022_alter_order_order_id_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='F9F15AF6DA', max_length=10, unique=True),
        ),
    ]
