# Generated by Django 5.1.7 on 2025-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0025_alter_referral_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='D3CB2C6836', max_length=10, unique=True),
        ),
    ]
