# Generated by Django 5.1.7 on 2025-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs_shop', '0026_remove_order_order_id_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='49B6D6BF14', max_length=10, unique=True),
        ),
    ]
